# Generated by Django 5.1.4 on 2025-01-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
                ('intro_firstname', models.CharField(max_length=10)),
                ('intro_middlename', models.CharField(max_length=10)),
                ('intro_lastname', models.CharField(max_length=10)),
                ('intro_image', models.FileField(default=None, null=True, upload_to='')),
                ('intro_designation', models.CharField(max_length=10)),
                ('intro_address', models.TextField()),
                ('intro_email', models.EmailField(max_length=254)),
                ('intro_phone', models.CharField(max_length=13)),
                ('intro_summary', models.CharField(max_length=50)),
                ('achi_title', models.CharField(max_length=20)),
                ('achi_description', models.TextField()),
                ('exp_title', models.CharField(max_length=20)),
                ('exp_company', models.CharField(max_length=20)),
                ('exp_location', models.CharField(max_length=20)),
                ('exp_start_date', models.DateField()),
                ('exp_end_date', models.DateField()),
                ('exp_description', models.TextField()),
                ('edu_school', models.CharField(max_length=20)),
                ('edu_degree', models.CharField(max_length=20)),
                ('edu_city', models.CharField(max_length=20)),
                ('edu_start_date', models.DateField()),
                ('edu_end_date', models.DateField()),
                ('edu_description', models.TextField()),
                ('proj_name', models.CharField(max_length=20)),
                ('proj_link', models.TextField()),
                ('proj_description', models.TextField()),
                ('skills', models.TextField()),
            ],
        ),
    ]
