# Generated by Django 5.1.4 on 2025-01-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='achi_description',
            field=models.TextField(verbose_name='Enter  Achievement Description'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='achi_title',
            field=models.CharField(max_length=20, verbose_name='Enter  Achievement Title'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='edu_city',
            field=models.CharField(max_length=20, verbose_name='Enter  Education City'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='edu_degree',
            field=models.CharField(max_length=20, verbose_name='Enter  Education Degree'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='edu_description',
            field=models.TextField(verbose_name='Enter  Education Description'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='edu_end_date',
            field=models.DateField(verbose_name='Enter  Education End Date'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='edu_school',
            field=models.CharField(max_length=20, verbose_name='Enter  Education School'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='edu_start_date',
            field=models.DateField(verbose_name='Enter  Education Start Date'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='exp_company',
            field=models.CharField(max_length=20, verbose_name='Enter  Experience Company'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='exp_description',
            field=models.TextField(verbose_name='Enter  Experience Description'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='exp_end_date',
            field=models.DateField(verbose_name='Enter  Experience End Date'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='exp_location',
            field=models.CharField(max_length=20, verbose_name='Enter  Experience Location'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='exp_start_date',
            field=models.DateField(verbose_name='Enter  Experience Start Date'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='exp_title',
            field=models.CharField(max_length=20, verbose_name='Enter  Experience Title'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='intro_address',
            field=models.TextField(verbose_name='Enter User Address'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='intro_designation',
            field=models.CharField(max_length=10, verbose_name='Enter  Designation'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='intro_email',
            field=models.EmailField(max_length=254, verbose_name='Enter User Email'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='intro_firstname',
            field=models.CharField(max_length=10, verbose_name='Enter FirstName'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='intro_image',
            field=models.FileField(default=None, null=True, upload_to='', verbose_name='Enter User Image'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='intro_lastname',
            field=models.CharField(max_length=10, verbose_name='Enter LastName'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='intro_middlename',
            field=models.CharField(max_length=10, verbose_name='Enter MiddleName'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='intro_phone',
            field=models.CharField(max_length=13, verbose_name='Enter User Mobile Number'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='intro_summary',
            field=models.CharField(max_length=50, verbose_name='Enter User Summary'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='password',
            field=models.CharField(max_length=20, verbose_name='Enter Password'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='proj_description',
            field=models.TextField(verbose_name='Enter  Project Description'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='proj_link',
            field=models.TextField(verbose_name='Enter  Project Link'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='proj_name',
            field=models.CharField(max_length=20, verbose_name='Enter  Project Name'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='skills',
            field=models.TextField(verbose_name='Enter Name'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='username',
            field=models.CharField(max_length=15, verbose_name='Enter UserName'),
        ),
    ]
