# Generated by Django 5.1.4 on 2025-01-17 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_alter_user_data_achi_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='password',
        ),
    ]
