# Generated by Django 5.1.4 on 2025-01-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0004_alter_user_data_achi_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='achi_title',
            field=models.CharField(default='', max_length=50, verbose_name='Enter  Achievement Title'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='edu_city',
            field=models.CharField(default='', max_length=50, verbose_name='Enter  Education City'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='edu_degree',
            field=models.CharField(default='', max_length=50, verbose_name='Enter  Education Degree'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='edu_school',
            field=models.CharField(default='', max_length=50, verbose_name='Enter  Education School'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='exp_company',
            field=models.CharField(default='', max_length=50, verbose_name='Enter  Experience Company'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='exp_location',
            field=models.CharField(default='', max_length=50, verbose_name='Enter  Experience Location'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='exp_title',
            field=models.CharField(default='', max_length=50, verbose_name='Enter  Experience Title'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='intro_firstname',
            field=models.CharField(default='', max_length=50, verbose_name='Enter FirstName'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='intro_lastname',
            field=models.CharField(default='', max_length=50, verbose_name='Enter LastName'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='intro_middlename',
            field=models.CharField(default='', max_length=50, verbose_name='Enter MiddleName'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='intro_phone',
            field=models.CharField(default='', max_length=50, verbose_name='Enter User Mobile Number'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='proj_link',
            field=models.CharField(default='', max_length=50, verbose_name='Enter  Project Link'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='proj_name',
            field=models.CharField(default='', max_length=50, verbose_name='Enter  Project Name'),
        ),
    ]
