# Generated by Django 5.1.4 on 2025-01-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0005_alter_user_data_achi_title_alter_user_data_edu_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='achi_description',
            field=models.TextField(default='', verbose_name='Achievement Description'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='achi_title',
            field=models.CharField(default='', max_length=50, verbose_name='Achievement Title'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='edu_city',
            field=models.CharField(default='', max_length=50, verbose_name='Education City'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='edu_degree',
            field=models.CharField(default='', max_length=50, verbose_name='Education Degree'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='edu_description',
            field=models.TextField(default='', verbose_name='Education Description'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='edu_end_date',
            field=models.DateField(default='', verbose_name='Education End Date'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='edu_school',
            field=models.CharField(default='', max_length=50, verbose_name='Education School'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='edu_start_date',
            field=models.DateField(default='', verbose_name='Education Start Date'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='exp_company',
            field=models.CharField(default='', max_length=50, verbose_name='Experience Company'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='exp_description',
            field=models.TextField(default='', verbose_name='Experience Description'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='exp_end_date',
            field=models.DateField(default='', verbose_name='Experience End Date'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='exp_location',
            field=models.CharField(default='', max_length=50, verbose_name='Experience Location'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='exp_start_date',
            field=models.DateField(default='', verbose_name='Experience Start Date'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='exp_title',
            field=models.CharField(default='', max_length=50, verbose_name='Experience Title'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='intro_address',
            field=models.TextField(default='', verbose_name='User Address'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='intro_designation',
            field=models.TextField(default='', verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='intro_email',
            field=models.EmailField(default='', max_length=254, verbose_name='User Email'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='intro_firstname',
            field=models.CharField(default='', max_length=50, verbose_name='FirstName'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='intro_image',
            field=models.FileField(default=None, null=True, upload_to='', verbose_name='User Image'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='intro_lastname',
            field=models.CharField(default='', max_length=50, verbose_name='LastName'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='intro_middlename',
            field=models.CharField(default='', max_length=50, verbose_name='MiddleName'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='intro_phone',
            field=models.CharField(default='', max_length=50, verbose_name='User Mobile Number'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='intro_summary',
            field=models.TextField(default='', verbose_name='User Summary'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='proj_description',
            field=models.TextField(default='', verbose_name='Project Description'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='proj_link',
            field=models.CharField(default='', max_length=50, verbose_name='Project Link'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='proj_name',
            field=models.CharField(default='', max_length=50, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='skills',
            field=models.TextField(default='', verbose_name='your Skills'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='username',
            field=models.TextField(default='', verbose_name='UserName'),
        ),
    ]
