# Generated by Django 5.1.4 on 2025-01-17 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0006_alter_user_data_achi_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='edu_end_date',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Education End Date'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='edu_start_date',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Education Start Date'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='exp_end_date',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Experience End Date'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='exp_start_date',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Experience Start Date'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='intro_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='', verbose_name='User Image'),
        ),
    ]
