# Generated by Django 5.1.4 on 2025-01-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0008_alter_user_data_edu_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='edu_end_date',
            field=models.JSONField(blank=True, null=True, verbose_name='Education End Date'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='edu_start_date',
            field=models.JSONField(blank=True, null=True, verbose_name='Education Start Date'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='exp_end_date',
            field=models.JSONField(blank=True, null=True, verbose_name='Experience End Date'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='exp_start_date',
            field=models.JSONField(blank=True, null=True, verbose_name='Experience Start Date'),
        ),
    ]
