# Generated by Django 5.1.5 on 2025-01-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0011_alter_user_data_intro_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='achi_description',
            field=models.TextField(default=list, verbose_name='Achievement Description'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='achi_title',
            field=models.CharField(default=list, max_length=50, verbose_name='Achievement Title'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='edu_city',
            field=models.CharField(default=list, max_length=50, verbose_name='Education City'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='edu_degree',
            field=models.CharField(default=list, max_length=50, verbose_name='Education Degree'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='edu_description',
            field=models.TextField(default=list, verbose_name='Education Description'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='edu_school',
            field=models.CharField(default=list, max_length=50, verbose_name='Education School'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='exp_company',
            field=models.CharField(default=list, max_length=50, verbose_name='Experience Company'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='exp_description',
            field=models.TextField(default=list, verbose_name='Experience Description'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='exp_location',
            field=models.CharField(default=list, max_length=50, verbose_name='Experience Location'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='exp_title',
            field=models.CharField(default=list, max_length=50, verbose_name='Experience Title'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='proj_description',
            field=models.TextField(default=list, verbose_name='Project Description'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='proj_link',
            field=models.CharField(default=list, max_length=50, verbose_name='Project Link'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='proj_name',
            field=models.CharField(default=list, max_length=50, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='skills',
            field=models.TextField(default=list, verbose_name='your Skills'),
        ),
    ]
